name: cleanup-resources
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  cleanup-resources:
   name: Cleanup Resources
   runs-on: ubuntu-latest
   steps:
     - name: Get PR number
       run: echo "PR number is ${{ github.event.number }}"