name: deploy


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: choice
        options:
          - development
          - production
      version:
        description: 'The required version'
        type: string
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'development' }}
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         ref: ${input.version}
         
     - name: cat
       run: cat ./github/workflows/deploy.yml
       

