name: deploy


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: string
      version:
        description: 'The version to deploy'
        required: true
        type: string
jobs:
  deploy:
    name: deploy
    runs-on: linux-platform-eng
    steps:
     - name: deploy
       run: echo "Deploying ${{ inputs.environment }} on version ${{ inputs.version }}"
       

