name: deploy


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: string
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-tags: true
         fetch-depth: 0
     - name: ls
       run: ls -la
     - name: deploy
       run: echo "Deploying ${{ inputs.environment }} on version ${{ github.ref_name }}"
       

