name: deploy-artifact
on:
  workflow_run:
    workflows: ["deploy"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from Workflow A
        uses: actions/download-artifact@v4
        with:
          name: workflow-data
          run-id: ${{ github.event.workflow_run.id }}
          github-token: 
      - name: Read the inputs
        run: |
          ENV_VALUE=$(cat env_name.txt)
          echo "The passed environment is $ENV_VALUE"
